{"uid":"89f19173916b0d85","name":"Test create entity","fullName":"tests.api.test_api.TestEntityAPI#test_create_entity","historyId":"4fc7e178233ca1b1d3084d53a584f20d","time":{"start":1727257935168,"stop":1727257935168,"duration":0},"description":"Verify that an entity can be created successfully","descriptionHtml":"<p>Verify that an entity can be created successfully</p>\n","status":"broken","statusMessage":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","statusTrace":"api_client = <services.entity.api_client.APIClient object at 0x7fa1c7ee8260>\n\n    @pytest.fixture\n    def entity_id(api_client: APIClient) -> str:\n        \"\"\"Fixture to create and yield a new entity ID.\"\"\"\n>       entity_id = api_client.create_entity()\n\nconftest.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/entity/api_client.py:21: in create_entity\n    response.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [404]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create\n\n/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/requests/models.py:1024: HTTPError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_skip_sensitive","time":{"start":1727257935169,"stop":1727257935169,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"entity_id","time":{"start":1727257935169,"stop":1727257935205,"duration":36},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/TestNest/TestNest/conftest.py\", line 18, in entity_id\n    entity_id = api_client.create_entity()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/TestNest/TestNest/services/entity/api_client.py\", line 21, in create_entity\n    response.raise_for_status()\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[{"name":"Create entity","time":{"start":1727257935169,"stop":1727257935205,"duration":36},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/TestNest/TestNest/services/entity/api_client.py\", line 21, in create_entity\n    response.raise_for_status()\n  File \"/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[{"uid":"d64eb3d6726034ba","name":"API Response","source":"d64eb3d6726034ba.txt","type":"text/plain","size":2430},{"uid":"6c23434a49de4cef","name":"Status Code","source":"6c23434a49de4cef.txt","type":"text/plain","size":3},{"uid":"1c5dafaf53dcabe5","name":"Headers","source":"1c5dafaf53dcabe5.txt","type":"text/plain","size":197}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":3,"hasContent":true,"attachmentStep":false},{"name":"api_client","time":{"start":1727257935169,"stop":1727257935169,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Verify that an entity can be created successfully","status":"broken","statusMessage":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","statusTrace":"api_client = <services.entity.api_client.APIClient object at 0x7fa1c7ee8260>\n\n    @pytest.fixture\n    def entity_id(api_client: APIClient) -> str:\n        \"\"\"Fixture to create and yield a new entity ID.\"\"\"\n>       entity_id = api_client.create_entity()\n\nconftest.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/entity/api_client.py:21: in create_entity\n    response.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [404]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create\n\n/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/site-packages/requests/models.py:1024: HTTPError","steps":[],"attachments":[{"uid":"76b36d92fedadba4","name":"log","source":"76b36d92fedadba4.txt","type":"text/plain","size":1571},{"uid":"d8c913e6d9249df4","name":"stderr","source":"d8c913e6d9249df4.txt","type":"text/plain","size":1254}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"Entity Management"},{"name":"feature","value":"CRUD Operations"},{"name":"severity","value":"critical"},{"name":"tag","value":"api"},{"name":"parentSuite","value":"tests.api"},{"name":"suite","value":"test_api"},{"name":"subSuite","value":"TestEntityAPI"},{"name":"host","value":"fv-az1490-494"},{"name":"thread","value":"2253-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api.test_api"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"33b23885312622d2","status":"broken","statusDetails":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","time":{"start":1727257930113,"stop":1727257930113,"duration":0}},{"uid":"efdbc272c72f43d1","status":"broken","statusDetails":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","time":{"start":1727257925059,"stop":1727257925059,"duration":0}},{"uid":"c83534ba5f417d11","status":"broken","statusDetails":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","time":{"start":1727257920004,"stop":1727257920004,"duration":0}},{"uid":"81bf5b0576af7ff5","status":"broken","statusDetails":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","time":{"start":1727257914952,"stop":1727257914952,"duration":0}},{"uid":"3c0cf2e631c88ddd","status":"broken","statusDetails":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://a031-95-32-133-30.ngrok-free.app/api/create","time":{"start":1727257909714,"stop":1727257909714,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":3,"unknown":0,"total":4},"items":[{"uid":"8ca79a24bfc8b937","reportUrl":"https://ZhikharevAl.github.io/TestNest/7//#testresult/8ca79a24bfc8b937","status":"passed","time":{"start":1727235454935,"stop":1727235454935,"duration":0}},{"uid":"a7b1d1a46952b95b","reportUrl":"https://ZhikharevAl.github.io/TestNest/6//#testresult/a7b1d1a46952b95b","status":"passed","time":{"start":1727234275506,"stop":1727234275507,"duration":1}},{"uid":"6e0be8d53994f8ef","reportUrl":"https://ZhikharevAl.github.io/TestNest/5//#testresult/6e0be8d53994f8ef","status":"passed","time":{"start":1727230686016,"stop":1727230686016,"duration":0}}]},"tags":["api"]},"source":"89f19173916b0d85.json","parameterValues":[]}